### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by limzykenneth** [earlymarket/Coposition#222]
Would be great to have some content for the landing page. Specifically, a short video to go on the first section kinda like InVision's site, a couple photos/images as background images for the parallax sections and also any additional content that would be required to go on the landing page.

**Comment by GarySiu** [comment]
I agree but I don't know who would be responsible for sourcing or creating it. We have a graphic designer on staff for other projects. Wait till Monday for the other's to get back into the office?

**Comment by limzykenneth** [comment]
Yup, that's fine. Cheers.
