### ISSUE TITLE
Styling branch: navbar and menu readibility

### ISSUE THREAD

**Issue by GarySiu** [earlymarket/CoPosition#224]
These are currently default. Navbar probably wants custom classes for the dropdowns when in the transparent state. The pushpin'd ul on the right is also difficult to read when overlaying images or other elements.

**Comment by limzykenneth** [comment]
Fixing the pushpin at the moment, might give them a semi-transparent background, see what works. I'm considering not using the dropdowns for the navbar except on smaller screens. Will update soon.
