### ISSUE TITLE
Checkin#get_data overwrites checkin data if you change from unfogged -> fogged

### ISSUE THREAD

**Issue by GarySiu** [earlymarket/Coposition#284]

**Comment by t-harps** [comment]
get_data returns the fogged lat/lng/address but the Checkin itself is unchanged. 
If you call it on a variable the variable does get overwritten, but the actual Checkin does not.
i.e.
Checkin.last.update(fogged:true) 
Checkin.last.get_data = fogged data
Checkin.last = unfogged data.
