### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by limzykenneth** [earlymarket/Coposition#312]
@GarySiu @t-harps I'm wondering if the test can be modified a bit so that it either look for css selector to click on or if it can handle objects with duplicate names? The reason is that the mobile navigation for materializecss do it in such a way that the mobile nav is defined as a separate DOM element and consequently with duplicate items as the normal navbar. The test fail if I enabled the mobile nav and I'm not familiar with this test suite at the moment.

**Comment by GarySiu** [comment]
It'll take a look tomorrow but the docs say there is a css matcher: http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/RSpecMatchers

**Comment by t-harps** [comment]
Can you push up the stuff you're working on so we can see how the tests are failing?

**Comment by limzykenneth** [comment]
Pushed to the styling branch

**Comment by t-harps** [comment]
Tests are passing for me as long as I have a link to the dashboard in the navbar, not sure I understand what the problem with the mobile navigation is? 
Tests are failing due to the dashboard link not being in the navbar anymore.

Or are you saying you want to write tests for the mobile navigation?

**Comment by limzykenneth** [comment]
Hmm...I remember it failed because of some error about ambiguous definition or something. I'll ping you guys again if there is a problem. I guess for now it's just the dashboard link then.

**Comment by t-harps** [comment]
Ah it might actually be because we updated all the gems, perhaps the latest version of capybara no longer makes a fuss when there's more than one link with the same name.

**Comment by limzykenneth** [comment]
Ok, cool.
