### ISSUE TITLE
jquery page load events

### ISSUE THREAD

**Issue by limzykenneth** [earlymarket/Coposition#336]
Currently most of the page use

```
$(document).on('ready page:change', function() {
});
```

for jquery page load event but since it is listening for two events sometimes it will run twice, resulting in a double binding of events and duplicate of elements (in the case of d3 which I'm using now for the dashboard).

I tried removing the `ready` event and it seem to work as expected. If nothing breaks I'll switch all of them to use only `page:change` event.

**Comment by GarySiu** [comment]
I came across the same problem and did the same thing. Doesn't seem to break anything so far and tried to manually test a few different scenarios.
