### ISSUE TITLE
Problem running tests on Firefox

### ISSUE THREAD

**Issue by limzykenneth** [earlymarket/Coposition#360]
I've updated my Firefox to the latest version (45.0.1) and the tests seem to be stuck at this screen at the beginning
![screen shot 2016-04-02 at 5 31 50 pm](https://cloud.githubusercontent.com/assets/7543950/14227578/f9958b52-f8f8-11e5-80e3-94e71d8a0e61.png)

**Comment by t-harps** [comment]
Oh god this is back, I had the same issue and tried everything under the sun to fix it, eventually just ended up having to roll my firefox back to the previous version.
I just pushed up a branch called update selenium, try going onto that branch, running bundle and see if that solves the problem. If not you may just have to stick to the older version of firefox...

**Comment by limzykenneth** [comment]
Ok, I'll try it tonight. :open_mouth:

**Comment by limzykenneth** [comment]
I didn't find the update selenium branch, have you pushed it up?

**Comment by GarySiu** [comment]
https://github.com/earlymarket/Coposition/tree/update-selenium

**Comment by limzykenneth** [comment]
Just tried the branch, working now :+1:
