### ISSUE TITLE
Fix Device index page bug

### ISSUE THREAD

**Issue by t-harps** [earlymarket/CoPosition#42]
Nicely resolve the bug: Device index page breaks when a device has no checkins

**Comment by earlymarket** [comment]
Can you add a complexity estimate to new issues.  We can either use days as units or story points.

**Comment by t-harps** [comment]
Do you have any preference? I think we will try the system Dan mentioned, 
1 = something we know how to do
2 = something that may require a bit of research
3 = something that will definitely require research, new things we haven't used before.

**Comment by earlymarket** [comment]
OK let;'s try this.  Please assign estimates to all tickets.
