### ISSUE TITLE
Shared devices not showing checkins

### ISSUE THREAD

**Issue by dansteele** [earlymarket/Coposition#448]
Shared this device: https://coposition.com/users/dansteele/devices/131/shared
However, I can't see any checkins at that URL ^ (which I assume I should)

App is looking awesome guys!

**Comment by t-harps** [comment]
Forgot to migrate >.<
Thanks Dan, should be fixed now.

**Comment by dansteele** [comment]
@t-harps 
Might be worth looking at https://docs.travis-ci.com/user/deployment/ and getting Travis to deploy directly to Heroku.
That way Travis can run post deploy scripts for you. Namely, that might be
`rake db:migrate && rake assets:clobber && rake assets:precompile`
