### ISSUE TITLE
Register device with copo automatically

### ISSUE THREAD

**Issue by earlymarket** [earlymarket/CoPosition#51]
Please advise if this is via an API command

**Comment by GarySiu** [comment]
The functionality doesn't exist in the API yet. Dan suggested we think about how to implement it but we don't really understand how the android app uses the api at the moment.

**Comment by GarySiu** [comment]
Adding Dan's workflow notes for the record

1. App opens

2. Ask coposition for a new unique UUID in background on start

	```
	URL:
	   GET http://api.coposition.com/v1/uuid
		
	Headers:
	   X-Api-Key: 0577722...
	```

3. User enters email/password in a form

	```
	URL:
		POST http://coposition.com/users/sign_in
	
	Headers:
	   X-Secret-App-Key: some-key-that-ill-give
	   Accept: application/json
	Payload:
		{
			"user": {
			   "email": "dan@dan.com"
			}
		}
	```
4. Store the `authentication_token` returned

5. Create a device by binding the user to the UUID

	```
	URL:
		POST http://coposition.com/users/dansteele/devices
		
	Headers:
	   X-Api-Key: 05777...
	   X-User-Email: dan@dan.com
	   X-User-Token: vGRf...
	   
	Payload:
		{
			"device": {
				"uuid": "2213..." 
			}
		}		
	```
6. Send checkin(s) to CoPosition every 10 seconds

	```
	URL:
		POST http://api.coposition.com/v1/checkins
	
	Headers:
		None needed
		
	Payload: 
		{
			"checkin": {
				"uuid": "123",
				"lat": "50",
				"lng": "-1" 
			}
		}
	```
7. Display a START and STOP button

8. Display a LOGOUT button

**Comment by GarySiu** [comment]
Tom and I stepped through the procedure and the API (mostly) works fine. Not entirely sure why the android app doesn't register the device with the user?

**Comment by GarySiu** [comment]
Two issues:

1) Every time the app is run, an empty device (one without any information beyond UUID) is created regardless of any other conditions. In my opinion the app does not need to get a UUID and one shouldn't be created until after signin.

2) We aren't uniquely identifying the device after we create it. A device could potentially have multiple UUIDs. Also every single time an app user signs in they will be asked to create a new device or select from a pre-existing one. It would be better if the app knew if the device was already registered. Perhaps we could use the IMEI for a mobile/tablet device?

**Comment by t-harps** [comment]
Android Developer instructions:
1. Implement "step five" - Create a device by binding the user to the UUID
2. Move getting UUID step till after login (temporary fix).
3. Implement getting the device IMEI.
4. Use the IMEI to check whether the device already exists in CoPosition, create a new device if not.

Our end:
1. Add new IMEI field in device so that mobile devices can be identified uniquely.
2. Change device creation so that through the app, the IMEI is checked and a UUID created (if necessary) all in one step, thus removing empty device creation.

**Comment by GarySiu** [comment]
We both now have working redmine access. I'm writing a short series of diagnostic steps to work out where the android devs are at.
