### ISSUE TITLE
Change APP requests so either all or none must be JSON

### ISSUE THREAD

**Issue by t-harps** [earlymarket/CoPosition#63]
Sign in currently checks if the request is in JSON, no other app requests have this requirement, either remove requirement or add to all other app requests.

**Comment by GarySiu** [comment]
The check seems to be if the client is capable of accepting JSON. So it would make sense to check this when the client is first signing in? Should I amend the error message to reflect this?

**Comment by dansteele** [comment]
Let's remove this requirement
