### ISSUE TITLE
Need a way to stop emails

### ISSUE THREAD

**Issue by dansteele** [earlymarket/Coposition#710]
:wave: 
Need a way to 'mute device' and simply unsubscribe to emails :) 
Otherwise your domain will be blacklisted pretty rapidly

I recommend using a service like MailChimp to do your email heavy lifting if you're not already :)

**Comment by t-harps** [comment]
Thanks Dan, working on this soon, should be done before you get another email!

**Comment by dansteele** [comment]
Haven't got one in a while ;)
