### ISSUE TITLE
Send Slack alert to dev

### ISSUE THREAD

**Issue by earlymarket** [earlymarket/CoPosition#99]
Send slack alert on events
https://api.slack.com/community
Token is on 1password

**Comment by t-harps** [comment]
Functionality is built, would just like to know what events need notifications ideally, and how much info to send across. 
E.g when a new user registers, username+email? or no specific info, just that it's taken place.

**Comment by dansteele** [comment]
@t-harps @earlymarket I wouldn't send that info; we want to reassure that everyone's email is private, and isn't publicised anywhere.
Privacy is our thang
